name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check
      run: cargo check --verbose

    - name: Build
      run: cargo build --verbose

    - name: Tests
      run: cargo test --verbose

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Format
      run: cargo fmt -- --check

    - name: Check Dependencies for Vulnerabilities
      run: cargo audit

    - name: Publish Artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          target/debug/
